---
title: "CodeBook"
author: "Mazena"
date: "11/5/2020"
output: html_document
---

##Code Book for the Assignment

##Dataset has been downloaded from "https://d396qusza40orc.cloudfront.net/getdata%2Fprojectfiles%2FUCI%20HAR%20Dataset.zip"

##This is a publicly avalaible dataset

##Following variables are included:

##subject activity 

##timeDomainBodyAccelerometerMeanX 

##timeDomainBodyAccelerometerMeanY 

##timeDomainBodyAccelerometerMeanZ 

##timeDomainBodyAccelerometerStandardDeviationX


##timeDomainBodyAccelerometerStandardDeviationY
##timeDomainBodyAccelerometerStandardDeviationZ


##timeDomainGravityAccelerometerMeanX 


##timeDomainGravityAccelerometerMeanY 
##timeDomainGravityAccelerometerMeanZ 

##timeDomainGravityAccelerometerStandardDeviationX 

##timeDomainGravityAccelerometerStandardDeviationY 

##timeDomainGravityAccelerometerStandardDeviationZ 
##timeDomainBodyAccelerometerJerkMeanX 

##timeDomainBodyAccelerometerJerkMeanY timeDomainBodyAccelerometerJerkMeanZ 

##timeDomainBodyAccelerometerJerkStandardDeviationX ##timeDomainBodyAccelerometerJerkStandardDeviationY

##timeDomainBodyAccelerometerJerkStandardDeviationZ 
##timeDomainBodyGyroscopeMeanX 


##timeDomainBodyGyroscopeMeanY 
##timeDomainBodyGyroscopeMeanZ 


##timeDomainBodyGyroscopeStandardDeviationX

##timeDomainBodyGyroscopeStandardDeviationY

##timeDomainBodyGyroscopeStandardDeviationZ 


##timeDomainBodyGyroscopeJerkMeanX 


##timeDomainBodyGyroscopeJerkMeanY 


##timeDomainBodyGyroscopeJerkMeanZ 


##timeDomainBodyGyroscopeJerkStandardDeviationX

##timeDomainBodyGyroscopeJerkStandardDeviationY

##timeDomainBodyGyroscopeJerkStandardDeviationZ

##timeDomainBodyAccelerometerMagnitudeMean

##timeDomainBodyAccelerometerMagnitudeStandardDeviation ##timeDomainGravityAccelerometerMagnitudeMean

##timeDomainGravityAccelerometerMagnitudeStandardDeviation  

##timeDomainBodyAccelerometerJerkMagnitudeMean

##timeDomainBodyAccelerometerJerkMagnitudeStandardDeviation

##timeDomainBodyGyroscopeMagnitudeMean

##timeDomainBodyGyroscopeMagnitudeStandardDeviation

##timeDomainBodyGyroscopeJerkMagnitudeMean

##timeDomainBodyGyroscopeJerkMagnitudeStandardDeviation

##frequencyDomainBodyAccelerometerMeanX


##frequencyDomainBodyAccelerometerMeanY


##frequencyDomainBodyAccelerometerMeanZ

##frequencyDomainBodyAccelerometerStandardDeviationX

##frequencyDomainBodyAccelerometerStandardDeviationY

##frequencyDomainBodyAccelerometerStandardDeviationZ

##frequencyDomainBodyAccelerometerMeanFrequencyX

##frequencyDomainBodyAccelerometerMeanFrequencyY

##frequencyDomainBodyAccelerometerMeanFrequencyZ

##frequencyDomainBodyAccelerometerJerkMeanX

##frequencyDomainBodyAccelerometerJerkMeanY

##frequencyDomainBodyAccelerometerJerkMeanZ

##frequencyDomainBodyAccelerometerJerkStandardDeviationX

##frequencyDomainBodyAccelerometerJerkStandardDeviationY


##frequencyDomainBodyAccelerometerJerkStandardDeviationZ

##frequencyDomainBodyAccelerometerJerkMeanFrequencyX

##frequencyDomainBodyAccelerometerJerkMeanFrequencyY

##frequencyDomainBodyAccelerometerJerkMeanFrequencyZ


##frequencyDomainBodyGyroscopeMeanX

##frequencyDomainBodyGyroscopeMeanY 

##frequencyDomainBodyGyroscopeMeanZ

##frequencyDomainBodyGyroscopeStandardDeviationX

##frequencyDomainBodyGyroscopeStandardDeviationY

##frequencyDomainBodyGyroscopeStandardDeviationZ

##frequencyDomainBodyGyroscopeMeanFrequencyX

##frequencyDomainBodyGyroscopeMeanFrequencyY

##frequencyDomainBodyGyroscopeMeanFrequencyZ

##frequencyDomainBodyAccelerometerMagnitudeMean

##frequencyDomainBodyAccelerometerMagnitudeStandardDeviation

##frequencyDomainBodyAccelerometerMagnitudeMeanFrequency

##frequencyDomainBodyAccelerometerJerkMagnitudeMean

##frequencyDomainBodyAccelerometerJerkMagnitudeStandardDeviation

##frequencyDomainBodyAccelerometerJerkMagnitudeMeanFrequency

##frequencyDomainBodyGyroscopeMagnitudeMean

##frequencyDomainBodyGyroscopeMagnitudeStandardDeviation

##frequencyDomainBodyGyroscopeMagnitudeMeanFrequency

##frequencyDomainBodyGyroscopeJerkMagnitudeMean

##frequencyDomainBodyGyroscopeJerkMagnitudeStandardDeviation

##frequencyDomainBodyGyroscopeJerkMagnitudeMeanFrequency

##Data that is then saved in txt file that can be obtained by running the code in the script run_analysis.R
